# for slub_debug
qume_install/linux-5.12.4/init/Kconfig  # CONFIG_SLUB
qume_install/linux-5.12.4/lib/Kconfig.debug #CONFIG_SLUB_DEBUG_ON CONFIG_SLUB_STATS
cd linux-5.12.4/tools/vm
make ARCH=aarch64 CROSS_COMPILE=aarch64-linux-gnu-

# for kasan
linux-5.12.4/lib/Kconfig.kasan # KASAN HAVE_ARCH_KASAN KASAN_OUTLINE KASAN_INLINE HAVE_ARCH_KASAN_SW_TAGS HAVE_ARCH_KASAN_HW_TAGS CC_HAS_KASAN_GENERIC

// dead lock check
#LOCKUP_DETECTOR
#SOFTLOCKUP_DETECTOR
#BOOTPARAM_SOFTLOCKUP_PANIC
#BOOTPARAM_SOFTLOCKUP_PANIC_VALUE
#HARDLOCKUP_DETECTOR_PERF
#HARDLOCKUP_CHECK_TIMESTAMP
#HARDLOCKUP_DETECTOR
#BOOTPARAM_HARDLOCKUP_PANIC
#BOOTPARAM_HARDLOCKUP_PANIC_VALUE
#TEST_LOCKUP
#LOCK_DEBUGGING_SUPPORT
#PROVE_RAW_LOCK_NESTING
#DEBUG_SPINLOCK
#LOCKDEP
#LOCKDEP_SMALL
#DEBUG_LOCKDEP
#PROVE_LOCKING
lib/Kconfig.debug 
