# .bashrc
PS1="\[\e[35;1m\][\##i_linux:\w]\$\[\e[m"
# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ls="ls --color"

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
